[2024-04-22T06:38:47.597+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-22T06:38:47.748+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl.create_order_dataset scheduled__2024-04-18T00:00:00+00:00 [queued]>
[2024-04-22T06:38:47.865+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl.create_order_dataset scheduled__2024-04-18T00:00:00+00:00 [queued]>
[2024-04-22T06:38:47.869+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2024-04-22T06:38:48.046+0000] {taskinstance.py:2327} INFO - Executing <Task(BigQueryCreateEmptyDatasetOperator): create_order_dataset> on 2024-04-18 00:00:00+00:00
[2024-04-22T06:38:48.186+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=4335) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-04-22T06:38:48.200+0000] {standard_task_runner.py:63} INFO - Started process 4474 to run task
[2024-04-22T06:38:48.194+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'etl', 'create_order_dataset', 'scheduled__2024-04-18T00:00:00+00:00', '--job-id', '234', '--raw', '--subdir', 'DAGS_FOLDER/etl.py', '--cfg-path', '/tmp/tmp1wpaowon']
[2024-04-22T06:38:48.207+0000] {standard_task_runner.py:91} INFO - Job 234: Subtask create_order_dataset
[2024-04-22T06:38:48.592+0000] {task_command.py:426} INFO - Running <TaskInstance: etl.create_order_dataset scheduled__2024-04-18T00:00:00+00:00 [running]> on host af114bcfa67a
[2024-04-22T06:38:51.660+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl' AIRFLOW_CTX_TASK_ID='create_order_dataset' AIRFLOW_CTX_EXECUTION_DATE='2024-04-18T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-04-18T00:00:00+00:00'
[2024-04-22T06:38:51.672+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-22T06:38:51.715+0000] {connection.py:274} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2024-04-22T06:38:51.796+0000] {base.py:84} INFO - Using connection ID 'my_gcp_conn' for task execution.
[2024-04-22T06:38:52.484+0000] {bigquery.py:470} INFO - datasetId was not specified in `dataset_reference`. Will use default value order.
[2024-04-22T06:38:52.484+0000] {bigquery.py:470} INFO - projectId was not specified in `dataset_reference`. Will use default value dataengineer-415510.
[2024-04-22T06:38:52.485+0000] {bigquery.py:481} INFO - Creating dataset: order in project: dataengineer-415510 
[2024-04-22T06:38:53.795+0000] {bigquery.py:2045} INFO - Dataset order already exists.
[2024-04-22T06:38:53.823+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-22T06:38:53.841+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=etl, task_id=create_order_dataset, execution_date=20240418T000000, start_date=20240422T063847, end_date=20240422T063853
[2024-04-22T06:38:54.006+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-04-22T06:38:54.583+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-22T06:38:54.589+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
