[2024-04-14T08:22:15.154+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-14T08:22:15.167+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl.create_aggr_bq_table manual__2024-04-14T05:09:56.705108+00:00 [queued]>
[2024-04-14T08:22:15.176+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl.create_aggr_bq_table manual__2024-04-14T05:09:56.705108+00:00 [queued]>
[2024-04-14T08:22:15.176+0000] {taskinstance.py:2303} INFO - Starting attempt 6 of 6
[2024-04-14T08:22:15.193+0000] {taskinstance.py:2327} INFO - Executing <Task(BigQueryExecuteQueryOperator): create_aggr_bq_table> on 2024-04-14 05:09:56.705108+00:00
[2024-04-14T08:22:15.204+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=121456) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-04-14T08:22:15.203+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'etl', 'create_aggr_bq_table', 'manual__2024-04-14T05:09:56.705108+00:00', '--job-id', '75', '--raw', '--subdir', 'DAGS_FOLDER/etl.py', '--cfg-path', '/tmp/tmp6awyrz3z']
[2024-04-14T08:22:15.205+0000] {standard_task_runner.py:63} INFO - Started process 121483 to run task
[2024-04-14T08:22:15.205+0000] {standard_task_runner.py:91} INFO - Job 75: Subtask create_aggr_bq_table
[2024-04-14T08:22:15.244+0000] {task_command.py:426} INFO - Running <TaskInstance: etl.create_aggr_bq_table manual__2024-04-14T05:09:56.705108+00:00 [running]> on host 2ce858e27684
[2024-04-14T08:22:15.315+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl' AIRFLOW_CTX_TASK_ID='create_aggr_bq_table' AIRFLOW_CTX_EXECUTION_DATE='2024-04-14T05:09:56.705108+00:00' AIRFLOW_CTX_TRY_NUMBER='6' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-14T05:09:56.705108+00:00'
[2024-04-14T08:22:15.317+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-14T08:22:15.317+0000] {bigquery.py:1246} INFO - Executing: 
        CREATE OR REPLACE TABLE order.dataset_Finance AS
        SELECT
            No,
            paymenttype
        FROM `dataengineer-415510.order_bazilian.csv`
        
[2024-04-14T08:22:15.323+0000] {connection.py:274} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2024-04-14T08:22:15.328+0000] {base.py:84} INFO - Using connection ID 'my_gcp_conn' for task execution.
[2024-04-14T08:22:15.329+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/providers/google/cloud/operators/bigquery.py:1254 AirflowProviderDeprecationWarning: Call to deprecated method run_query. (Please use `***.providers.google.cloud.hooks.bigquery.BigQueryHook.insert_job`)
[2024-04-14T08:22:15.378+0000] {bigquery.py:1613} INFO - Inserting job ***_1713082935378256_8db3a988db790de4b0384045ad5bcac5
[2024-04-14T08:22:16.139+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-14T08:22:16.139+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/google/cloud/operators/bigquery.py", line 1254, in execute
    self.job_id = self.hook.run_query(
                  ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/deprecated/classic.py", line 285, in wrapper_function
    return wrapped_(*args_, **kwargs_)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/google/cloud/hooks/bigquery.py", line 2258, in run_query
    job = self.insert_job(configuration=configuration, project_id=self.project_id, location=location)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/google/common/hooks/base_google.py", line 485, in inner_wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/google/cloud/hooks/bigquery.py", line 1619, in insert_job
    job_api_repr.result(timeout=timeout, retry=retry)
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/bigquery/job/query.py", line 1590, in result
    do_get_result()
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/bigquery/job/query.py", line 1579, in do_get_result
    super(QueryJob, self).result(retry=retry, timeout=timeout)
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/bigquery/job/base.py", line 971, in result
    return super(_AsyncJob, self).result(timeout=timeout, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/google/api_core/future/polling.py", line 261, in result
    raise self._exception
google.api_core.exceptions.BadRequest: 400 Syntax error: Unexpected keyword ORDER at [2:33]; reason: invalidQuery, location: query, message: Syntax error: Unexpected keyword ORDER at [2:33]

Location: US
Job ID: airflow_1713082935378256_8db3a988db790de4b0384045ad5bcac5

[2024-04-14T08:22:16.149+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=etl, task_id=create_aggr_bq_table, execution_date=20240414T050956, start_date=20240414T082215, end_date=20240414T082216
[2024-04-14T08:22:16.165+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 75 for task create_aggr_bq_table (400 Syntax error: Unexpected keyword ORDER at [2:33]; reason: invalidQuery, location: query, message: Syntax error: Unexpected keyword ORDER at [2:33]

Location: US
Job ID: airflow_1713082935378256_8db3a988db790de4b0384045ad5bcac5
; 121483)
[2024-04-14T08:22:16.183+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-04-14T08:22:16.197+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-14T08:22:16.206+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
