[2024-04-14T08:17:08.968+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-14T08:17:08.981+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl.create_aggr_bq_table manual__2024-04-14T05:09:56.705108+00:00 [queued]>
[2024-04-14T08:17:08.987+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl.create_aggr_bq_table manual__2024-04-14T05:09:56.705108+00:00 [queued]>
[2024-04-14T08:17:08.987+0000] {taskinstance.py:2303} INFO - Starting attempt 4 of 4
[2024-04-14T08:17:09.001+0000] {taskinstance.py:2327} INFO - Executing <Task(BigQueryExecuteQueryOperator): create_aggr_bq_table> on 2024-04-14 05:09:56.705108+00:00
[2024-04-14T08:17:09.011+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=118761) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-04-14T08:17:09.011+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'etl', 'create_aggr_bq_table', 'manual__2024-04-14T05:09:56.705108+00:00', '--job-id', '69', '--raw', '--subdir', 'DAGS_FOLDER/etl.py', '--cfg-path', '/tmp/tmp85rp72w2']
[2024-04-14T08:17:09.012+0000] {standard_task_runner.py:63} INFO - Started process 118763 to run task
[2024-04-14T08:17:09.012+0000] {standard_task_runner.py:91} INFO - Job 69: Subtask create_aggr_bq_table
[2024-04-14T08:17:09.053+0000] {task_command.py:426} INFO - Running <TaskInstance: etl.create_aggr_bq_table manual__2024-04-14T05:09:56.705108+00:00 [running]> on host 2ce858e27684
[2024-04-14T08:17:09.137+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl' AIRFLOW_CTX_TASK_ID='create_aggr_bq_table' AIRFLOW_CTX_EXECUTION_DATE='2024-04-14T05:09:56.705108+00:00' AIRFLOW_CTX_TRY_NUMBER='4' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-14T05:09:56.705108+00:00'
[2024-04-14T08:17:09.138+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-14T08:17:09.139+0000] {bigquery.py:1246} INFO - Executing: CREATE OR REPLACE TABLE order.dataset_Finance          SELECT                 No,                paymenttype,         FROM dataengineer-415510.order_bazilian.csv
[2024-04-14T08:17:09.145+0000] {connection.py:274} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2024-04-14T08:17:09.149+0000] {base.py:84} INFO - Using connection ID 'my_gcp_conn' for task execution.
[2024-04-14T08:17:09.151+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/providers/google/cloud/operators/bigquery.py:1254 AirflowProviderDeprecationWarning: Call to deprecated method run_query. (Please use `***.providers.google.cloud.hooks.bigquery.BigQueryHook.insert_job`)
[2024-04-14T08:17:09.197+0000] {bigquery.py:1613} INFO - Inserting job ***_1713082629197428_2b161160c7d091db01e63c083529e561
[2024-04-14T08:17:09.874+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-14T08:17:09.875+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/google/cloud/operators/bigquery.py", line 1254, in execute
    self.job_id = self.hook.run_query(
                  ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/deprecated/classic.py", line 285, in wrapper_function
    return wrapped_(*args_, **kwargs_)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/google/cloud/hooks/bigquery.py", line 2258, in run_query
    job = self.insert_job(configuration=configuration, project_id=self.project_id, location=location)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/google/common/hooks/base_google.py", line 485, in inner_wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/google/cloud/hooks/bigquery.py", line 1619, in insert_job
    job_api_repr.result(timeout=timeout, retry=retry)
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/bigquery/job/query.py", line 1590, in result
    do_get_result()
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/bigquery/job/query.py", line 1579, in do_get_result
    super(QueryJob, self).result(retry=retry, timeout=timeout)
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/bigquery/job/base.py", line 971, in result
    return super(_AsyncJob, self).result(timeout=timeout, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/google/api_core/future/polling.py", line 261, in result
    raise self._exception
google.api_core.exceptions.BadRequest: 400 Syntax error: Unexpected keyword ORDER at [1:25]; reason: invalidQuery, location: query, message: Syntax error: Unexpected keyword ORDER at [1:25]

Location: US
Job ID: airflow_1713082629197428_2b161160c7d091db01e63c083529e561

[2024-04-14T08:17:09.888+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=etl, task_id=create_aggr_bq_table, execution_date=20240414T050956, start_date=20240414T081708, end_date=20240414T081709
[2024-04-14T08:17:09.904+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 69 for task create_aggr_bq_table (400 Syntax error: Unexpected keyword ORDER at [1:25]; reason: invalidQuery, location: query, message: Syntax error: Unexpected keyword ORDER at [1:25]

Location: US
Job ID: airflow_1713082629197428_2b161160c7d091db01e63c083529e561
; 118763)
[2024-04-14T08:17:09.950+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-04-14T08:17:09.976+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-14T08:17:09.984+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
