[2024-04-26T15:01:24.941+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-26T15:01:24.954+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dbt.dbt_task1 scheduled__2024-04-25T00:00:00+00:00 [queued]>
[2024-04-26T15:01:24.959+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dbt.dbt_task1 scheduled__2024-04-25T00:00:00+00:00 [queued]>
[2024-04-26T15:01:24.959+0000] {taskinstance.py:2303} INFO - Starting attempt 7 of 7
[2024-04-26T15:01:24.974+0000] {taskinstance.py:2327} INFO - Executing <Task(BashOperator): dbt_task1> on 2024-04-25 00:00:00+00:00
[2024-04-26T15:01:24.983+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dbt', 'dbt_task1', 'scheduled__2024-04-25T00:00:00+00:00', '--job-id', '367', '--raw', '--subdir', 'DAGS_FOLDER/bq_dbt.py', '--cfg-path', '/tmp/tmpyquhzc1x']
[2024-04-26T15:01:24.985+0000] {standard_task_runner.py:91} INFO - Job 367: Subtask dbt_task1
[2024-04-26T15:01:24.987+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=75154) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-04-26T15:01:24.988+0000] {standard_task_runner.py:63} INFO - Started process 75176 to run task
[2024-04-26T15:01:25.027+0000] {task_command.py:426} INFO - Running <TaskInstance: dbt.dbt_task1 scheduled__2024-04-25T00:00:00+00:00 [running]> on host b619dce40a27
[2024-04-26T15:01:25.089+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dbt' AIRFLOW_CTX_TASK_ID='dbt_task1' AIRFLOW_CTX_EXECUTION_DATE='2024-04-25T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='7' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-04-25T00:00:00+00:00'
[2024-04-26T15:01:25.090+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-26T15:01:25.091+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-04-26T15:01:25.092+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'cd /workspaces/dw-and-bi/Capstone-project && dbt run --models sales_report.sql']
[2024-04-26T15:01:25.108+0000] {subprocess.py:86} INFO - Output:
[2024-04-26T15:01:25.110+0000] {subprocess.py:93} INFO - /usr/bin/bash: line 1: cd: /workspaces/dw-and-bi/Capstone-project: No such file or directory
[2024-04-26T15:01:25.111+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2024-04-26T15:01:25.111+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-26T15:01:25.119+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-04-26T15:01:25.122+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=dbt, task_id=dbt_task1, execution_date=20240425T000000, start_date=20240426T150124, end_date=20240426T150125
[2024-04-26T15:01:25.135+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 367 for task dbt_task1 (Bash command failed. The command returned a non-zero exit code 1.; 75176)
[2024-04-26T15:01:25.162+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-04-26T15:01:25.177+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-26T15:01:25.185+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
