[2024-04-26T14:52:40.092+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-26T14:52:40.105+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dbt.dbt_task1 scheduled__2024-04-25T00:00:00+00:00 [queued]>
[2024-04-26T14:52:40.112+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dbt.dbt_task1 scheduled__2024-04-25T00:00:00+00:00 [queued]>
[2024-04-26T14:52:40.112+0000] {taskinstance.py:2303} INFO - Starting attempt 2 of 2
[2024-04-26T14:52:40.130+0000] {taskinstance.py:2327} INFO - Executing <Task(BashOperator): dbt_task1> on 2024-04-25 00:00:00+00:00
[2024-04-26T14:52:40.145+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=70437) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-04-26T14:52:40.146+0000] {standard_task_runner.py:63} INFO - Started process 70463 to run task
[2024-04-26T14:52:40.147+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dbt', 'dbt_task1', 'scheduled__2024-04-25T00:00:00+00:00', '--job-id', '362', '--raw', '--subdir', 'DAGS_FOLDER/bq_dbt.py', '--cfg-path', '/tmp/tmpgo33xpu2']
[2024-04-26T14:52:40.148+0000] {standard_task_runner.py:91} INFO - Job 362: Subtask dbt_task1
[2024-04-26T14:52:40.190+0000] {task_command.py:426} INFO - Running <TaskInstance: dbt.dbt_task1 scheduled__2024-04-25T00:00:00+00:00 [running]> on host b619dce40a27
[2024-04-26T14:52:40.256+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dbt' AIRFLOW_CTX_TASK_ID='dbt_task1' AIRFLOW_CTX_EXECUTION_DATE='2024-04-25T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-04-25T00:00:00+00:00'
[2024-04-26T14:52:40.257+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-26T14:52:40.258+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-04-26T14:52:40.258+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'dbt run --models sales_report.sql']
[2024-04-26T14:52:40.273+0000] {subprocess.py:86} INFO - Output:
[2024-04-26T14:52:40.275+0000] {subprocess.py:93} INFO - /usr/bin/bash: line 1: dbt: command not found
[2024-04-26T14:52:40.276+0000] {subprocess.py:97} INFO - Command exited with return code 127
[2024-04-26T14:52:40.276+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-26T14:52:40.283+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2024-04-26T14:52:40.286+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=dbt, task_id=dbt_task1, execution_date=20240425T000000, start_date=20240426T145240, end_date=20240426T145240
[2024-04-26T14:52:40.299+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 362 for task dbt_task1 (Bash command failed. The command returned a non-zero exit code 127.; 70463)
[2024-04-26T14:52:40.322+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-04-26T14:52:40.339+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-26T14:52:40.347+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
