[2024-04-26T16:19:04.599+0000] {task_context_logger.py:104} ERROR - Executor reports task instance <TaskInstance: dbt.git_install_task scheduled__2024-04-25T00:00:00+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
