[2024-04-26T16:09:06.513+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-26T16:09:06.526+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dbt.git_install_task scheduled__2024-04-25T00:00:00+00:00 [queued]>
[2024-04-26T16:09:06.532+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dbt.git_install_task scheduled__2024-04-25T00:00:00+00:00 [queued]>
[2024-04-26T16:09:06.532+0000] {taskinstance.py:2303} INFO - Starting attempt 3 of 3
[2024-04-26T16:09:06.546+0000] {taskinstance.py:2327} INFO - Executing <Task(BashOperator): git_install_task> on 2024-04-25 00:00:00+00:00
[2024-04-26T16:09:06.557+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=111197) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-04-26T16:09:06.557+0000] {standard_task_runner.py:63} INFO - Started process 111199 to run task
[2024-04-26T16:09:06.556+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dbt', 'git_install_task', 'scheduled__2024-04-25T00:00:00+00:00', '--job-id', '374', '--raw', '--subdir', 'DAGS_FOLDER/bq_dbt.py', '--cfg-path', '/tmp/tmpzhawc_az']
[2024-04-26T16:09:06.558+0000] {standard_task_runner.py:91} INFO - Job 374: Subtask git_install_task
[2024-04-26T16:09:06.599+0000] {task_command.py:426} INFO - Running <TaskInstance: dbt.git_install_task scheduled__2024-04-25T00:00:00+00:00 [running]> on host b619dce40a27
[2024-04-26T16:09:06.675+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dbt' AIRFLOW_CTX_TASK_ID='git_install_task' AIRFLOW_CTX_EXECUTION_DATE='2024-04-25T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-04-25T00:00:00+00:00'
[2024-04-26T16:09:06.677+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-26T16:09:06.678+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-04-26T16:09:06.678+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'echo <password> | sudo -S apt-get install git -y']
[2024-04-26T16:09:06.694+0000] {subprocess.py:86} INFO - Output:
[2024-04-26T16:09:06.696+0000] {subprocess.py:93} INFO - /usr/bin/bash: -c: line 1: syntax error near unexpected token `|'
[2024-04-26T16:09:06.696+0000] {subprocess.py:93} INFO - /usr/bin/bash: -c: line 1: `echo <password> | sudo -S apt-get install git -y'
[2024-04-26T16:09:06.697+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2024-04-26T16:09:06.697+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-26T16:09:06.704+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2024-04-26T16:09:06.707+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=dbt, task_id=git_install_task, execution_date=20240425T000000, start_date=20240426T160906, end_date=20240426T160906
[2024-04-26T16:09:06.721+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 374 for task git_install_task (Bash command failed. The command returned a non-zero exit code 2.; 111199)
[2024-04-26T16:09:06.731+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-04-26T16:09:06.743+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-26T16:09:06.749+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
