[2024-04-24T16:18:24.587+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-24T16:18:24.845+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl.gcs_to_bq_sellers scheduled__2024-04-22T00:00:00+00:00 [queued]>
[2024-04-24T16:18:24.913+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl.gcs_to_bq_sellers scheduled__2024-04-22T00:00:00+00:00 [queued]>
[2024-04-24T16:18:24.914+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2024-04-24T16:18:26.203+0000] {taskinstance.py:2327} INFO - Executing <Task(GCSToBigQueryOperator): gcs_to_bq_sellers> on 2024-04-22 00:00:00+00:00
[2024-04-24T16:18:26.329+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=688) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-04-24T16:18:26.330+0000] {standard_task_runner.py:63} INFO - Started process 804 to run task
[2024-04-24T16:18:26.284+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'etl', 'gcs_to_bq_sellers', 'scheduled__2024-04-22T00:00:00+00:00', '--job-id', '267', '--raw', '--subdir', 'DAGS_FOLDER/etl.py', '--cfg-path', '/tmp/tmpxuce0rty']
[2024-04-24T16:18:26.343+0000] {standard_task_runner.py:91} INFO - Job 267: Subtask gcs_to_bq_sellers
[2024-04-24T16:18:26.823+0000] {task_command.py:426} INFO - Running <TaskInstance: etl.gcs_to_bq_sellers scheduled__2024-04-22T00:00:00+00:00 [running]> on host af114bcfa67a
[2024-04-24T16:18:27.873+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl' AIRFLOW_CTX_TASK_ID='gcs_to_bq_sellers' AIRFLOW_CTX_EXECUTION_DATE='2024-04-22T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-04-22T00:00:00+00:00'
[2024-04-24T16:18:27.886+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-24T16:18:27.962+0000] {connection.py:274} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2024-04-24T16:18:27.984+0000] {base.py:84} INFO - Using connection ID 'my_gcp_conn' for task execution.
[2024-04-24T16:18:28.025+0000] {gcs_to_bigquery.py:379} INFO - Using existing BigQuery table for storing data...
[2024-04-24T16:18:28.662+0000] {bigquery.py:2328} INFO - Project is not included in destination_project_dataset_table: order.olist_sellers_dataset; using project "dataengineer-415510"
[2024-04-24T16:18:28.665+0000] {gcs_to_bigquery.py:383} INFO - Executing: {'load': {'autodetect': True, 'createDisposition': 'CREATE_IF_NEEDED', 'destinationTable': {'projectId': 'dataengineer-415510', 'datasetId': 'order', 'tableId': 'olist_sellers_dataset'}, 'sourceFormat': 'CSV', 'sourceUris': ['gs://swu-ds-525-112233/olist_sellers_dataset.csv'], 'writeDisposition': 'WRITE_TRUNCATE', 'ignoreUnknownValues': False, 'skipLeadingRows': None, 'fieldDelimiter': ',', 'quote': None, 'allowQuotedNewlines': False, 'encoding': 'UTF-8'}}
[2024-04-24T16:18:28.666+0000] {bigquery.py:1613} INFO - Inserting job ***_etl_gcs_to_bq_sellers_2024_04_22T00_00_00_00_00_f3166046f28c353415b4d61b6be16d1c
[2024-04-24T16:18:37.032+0000] {local_task_job_runner.py:124} ERROR - Received SIGTERM. Terminating subprocesses
[2024-04-24T16:18:37.037+0000] {process_utils.py:132} INFO - Sending 15 to group 804. PIDs of all processes in the group: [804]
[2024-04-24T16:18:37.038+0000] {process_utils.py:87} INFO - Sending the signal 15 to group 804
[2024-04-24T16:18:37.039+0000] {taskinstance.py:2607} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-04-24T16:18:37.714+0000] {bigquery.py:1504} INFO - Attempting to cancel job : dataengineer-415510, ***_etl_gcs_to_bq_sellers_2024_04_22T00_00_00_00_00_f3166046f28c353415b4d61b6be16d1c
[2024-04-24T16:18:38.825+0000] {bigquery.py:1525} INFO - Waiting for canceled job dataengineer-415510, ***_etl_gcs_to_bq_sellers_2024_04_22T00_00_00_00_00_f3166046f28c353415b4d61b6be16d1c to finish.
[2024-04-24T16:18:44.192+0000] {bigquery.py:1516} INFO - Job successfully canceled: dataengineer-415510, ***_etl_gcs_to_bq_sellers_2024_04_22T00_00_00_00_00_f3166046f28c353415b4d61b6be16d1c
[2024-04-24T16:18:44.193+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-24T16:18:44.208+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/google/api_core/retry/retry_unary.py", line 144, in retry_target
    result = target()
             ^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/google/api_core/future/polling.py", line 120, in _done_or_raise
    raise _OperationNotComplete()
google.api_core.future.polling._OperationNotComplete

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/google/cloud/transfers/gcs_to_bigquery.py", line 444, in execute
    job.result(timeout=self.result_timeout, retry=self.result_retry)
  File "/home/airflow/.local/lib/python3.12/site-packages/google/cloud/bigquery/job/base.py", line 971, in result
    return super(_AsyncJob, self).result(timeout=timeout, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/google/api_core/future/polling.py", line 256, in result
    self._blocking_poll(timeout=timeout, retry=retry, polling=polling)
  File "/home/airflow/.local/lib/python3.12/site-packages/google/api_core/future/polling.py", line 137, in _blocking_poll
    polling(self._done_or_raise)(retry=retry)
  File "/home/airflow/.local/lib/python3.12/site-packages/google/api_core/retry/retry_unary.py", line 293, in retry_wrapped_func
    return retry_target(
           ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/google/api_core/retry/retry_unary.py", line 164, in retry_target
    time.sleep(sleep)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 2609, in signal_handler
    raise AirflowTaskTerminated("Task received SIGTERM signal")
airflow.exceptions.AirflowTaskTerminated: Task received SIGTERM signal
[2024-04-24T16:18:44.247+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=etl, task_id=gcs_to_bq_sellers, execution_date=20240422T000000, start_date=20240424T161824, end_date=20240424T161844
[2024-04-24T16:18:44.331+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=804, status='terminated', exitcode=2, started='16:18:25') (804) terminated with exit code 2
[2024-04-24T16:18:44.332+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 143
[2024-04-24T16:18:44.348+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-24T16:18:44.373+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
